name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          cache: pip
      - run: python -m pip install poetry
      - run: poetry config virtualenvs.create false
      - run: python -m poetry install --no-root
      - uses: psf/black@stable
        with:
          options: "--check --verbose"