name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-apkg:
    runs-on: ubuntu-latest

    permissions: write-all
    
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: zip passfail3.ankiaddon __init__.py passfail2.py manifest.json LICENSE config.json config.md

      - run: gh release create "${{ github.ref }}" "passfail3.ankiaddon"