name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-apkg:
    runs-on: ubuntu-latest

    permissions: write-all
    
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: zip -j "passfail3-${{ env.RELEASE_VERSION }}.ankiaddon" src/* LICENSE
      - run: gh release create "${{ github.ref }}" "passfail3-${{ env.RELEASE_VERSION }}.ankiaddon"