name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-apkg:
    runs-on: ubuntu-latest

    permissions: write-all
    
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}

      - run: zip "passfail3-${{ RELEASE_VERSION }}.ankiaddon *.py manifest.json LICENSE config.json config.md
      - run: gh release create "${{ github.ref }}" "passfail3${{ RELEASE_VERSION }}.ankiaddon"